name = "cf-hack-mcp"
compatibility_date = "2025-02-04"
compatibility_flags = [ "nodejs_compat" ]

# [[d1_databases]]
# binding = "DB"
# database_name = "honc-d1-database"
# database_id = "local-honc-d1-database"
# migrations_dir = "drizzle/migrations"

[[d1_databases]]
binding = "DB"
database_name = "cf-hack-mcp-d1-database"
database_id = "6f07c140-c2ae-4aa2-8dba-1d95f33d8491"
migrations_dir = "drizzle/migrations"

# [vars]
# MY_VAR = "my-variable"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [ai]
# binding = "AI"
